/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Clases.Album;
import Clases.Artista;
import Clases.Cancion;
import Logica.Utilitario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author eefre
 */
public class frmCancion extends javax.swing.JFrame {

    ArrayList<Cancion> listaCanciones = Logica.Utilitario.listaCanciones;

    DefaultListModel modelo = new DefaultListModel();

    /**
     * Creates new form frmCancion
     */
    public frmCancion(frmPrincipal aThis, boolean par) {

        initComponents();
        cargarAlbumesEnComboBox();
        lstCanciones.setModel(modelo);
        //Linea para que no se salga
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstArtistas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnEditarArtista = new javax.swing.JButton();
        btnEliminarArtista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreArtista = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnSolista = new javax.swing.JRadioButton();
        rbtnBanda = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cmbGeneros = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtAnoInicial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtWeb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCantAlbumes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantCanciones = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();
        rbtnPausa = new javax.swing.JRadioButton();
        btnGuardarArtista = new javax.swing.JButton();
        btnMostrarArtista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstArtistas1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCanciones = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtGrabacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnEditarCancion = new javax.swing.JButton();
        btnEliminarCancion = new javax.swing.JButton();
        btnMostrarCancion = new javax.swing.JButton();
        btnGuardarCancion = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        txtSegundos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbAlbumes = new javax.swing.JComboBox<>();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstArtistas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstArtistas);

        jLabel2.setText("Mantenimiento de Artistas");

        btnEditarArtista.setText("Editar");

        btnEliminarArtista.setText("Eliminar");

        jLabel3.setText("Artistas");

        jLabel4.setText("Registrar Artista");

        txtNombreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArtistaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel6.setText("Tipo");

        rbtnSolista.setText("Solista");

        rbtnBanda.setText("Banda");

        jLabel7.setText("Géneros");

        jLabel8.setText("Año");

        jLabel9.setText("Origen");

        txtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenActionPerformed(evt);
            }
        });

        jLabel10.setText("Web");

        jLabel11.setText("Cantidad de Albumes");

        txtCantAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantAlbumesActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad de Canciones");

        txtCantCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantCancionesActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado Actual");

        rbtnActivo.setText("Activo");

        rbtnInactivo.setText("Inactivo");

        rbtnPausa.setText("Pausa");

        btnGuardarArtista.setText("Guardar Registro");

        btnMostrarArtista.setText("Mostrar");
        btnMostrarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnMostrarArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarArtista))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(rbtnSolista)
                                                .addGap(30, 30, 30)
                                                .addComponent(rbtnBanda))
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(txtNombreArtista)
                                                .addGap(18, 18, 18))))
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(26, 26, 26)
                                                .addComponent(txtCantAlbumes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbGeneros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtAnoInicial)))
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addGap(18, 18, 18)
                                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtOrigen)
                                                    .addComponent(txtWeb)))
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCantCanciones)))
                                        .addGap(18, 18, 18)))
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtnActivo)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtnInactivo)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbtnPausa)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addComponent(btnGuardarArtista)
                                .addGap(122, 122, 122))))))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbtnSolista)
                            .addComponent(rbtnBanda))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCantAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCantCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(rbtnInactivo)
                            .addComponent(rbtnPausa)
                            .addComponent(rbtnActivo))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarArtista)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarArtista)
                            .addComponent(btnEliminarArtista)
                            .addComponent(btnMostrarArtista))
                        .addGap(39, 39, 39))))
        );

        lstArtistas1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstArtistas1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mantenimiento Canciones");

        jLabel14.setText("Número");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lstCanciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstCanciones);

        jLabel15.setText("Seleccione un Álbum");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        jLabel16.setText("Titulo");

        txtMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosActionPerformed(evt);
            }
        });

        jLabel17.setText("Duracion");

        txtLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetraActionPerformed(evt);
            }
        });

        jLabel18.setText("Letra");

        txtGrabacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrabacionActionPerformed(evt);
            }
        });

        jLabel19.setText("Grabación");

        btnEditarCancion.setText("Editar");
        btnEditarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCancionActionPerformed(evt);
            }
        });

        btnEliminarCancion.setText("Eliminar");
        btnEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCancionActionPerformed(evt);
            }
        });

        btnMostrarCancion.setText("Mostar");
        btnMostrarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCancionActionPerformed(evt);
            }
        });

        btnGuardarCancion.setText("Guardar Registro");
        btnGuardarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCancionActionPerformed(evt);
            }
        });

        jLabel20.setText("Registrar Canción");

        btnActualizar.setText("Actualizar Registro");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel21.setText("Segundos");

        jLabel22.setText("Minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnMostrarCancion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarCancion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarCancion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(jLabel1)))
                        .addContainerGap(302, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(cmbAlbumes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnActualizar)
                                .addGap(21, 21, 21)
                                .addComponent(btnGuardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel22)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel21))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(21, 21, 21)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtGrabacion, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                                .addComponent(txtLetra)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cmbAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarCancion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCancion)
                    .addComponent(btnEditarCancion)
                    .addComponent(btnMostrarCancion))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArtistaActionPerformed

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    private void txtCantAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantAlbumesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantAlbumesActionPerformed

    private void txtCantCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantCancionesActionPerformed

    private void btnMostrarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarArtistaActionPerformed
        // Limpiar el modelo antes de agregar elementos

    }//GEN-LAST:event_btnMostrarArtistaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosActionPerformed

    private void txtLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetraActionPerformed

    private void txtGrabacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrabacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrabacionActionPerformed

    private void btnMostrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCancionActionPerformed
        cargarListaCanciones();
    }//GEN-LAST:event_btnMostrarCancionActionPerformed

    private void btnEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCancionActionPerformed
        eliminarCancionSeleccionada();
        cargarListaCanciones(); // Actualiza la interfaz después de eliminar
        JOptionPane.showMessageDialog(null, "Canción Eliminada");
    }//GEN-LAST:event_btnEliminarCancionActionPerformed

    private void btnEditarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCancionActionPerformed
        editarCancionSeleccionada();
    }//GEN-LAST:event_btnEditarCancionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarCancionSeleccionada();
        cargarListaCanciones();//Actualiza la interfaz después de actualizar
        limpiarFormulario();
        JOptionPane.showMessageDialog(null, "Datos de Canción Actualizados");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCancionActionPerformed
        crearCancion();
    }//GEN-LAST:event_btnGuardarCancionActionPerformed

    public void crearCancion() {
        // Verificar si se ha seleccionado un álbum
        if (cmbAlbumes.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Álbum", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si no se seleccionó un álbum
        }

        // Obtener el nombre del álbum seleccionado desde el JComboBox
        String nombreAlbumSeleccionado = cmbAlbumes.getSelectedItem().toString();

        // Buscar el álbum por nombre en la lista de álbumes
        Album albumSeleccionado = null;
        for (Album album : Utilitario.listaAlbum) {
            if (album.getNombre().equalsIgnoreCase(nombreAlbumSeleccionado)) {
                albumSeleccionado = album;
                break;
            }
        }

        // Verificar si se encontró el álbum
        if (albumSeleccionado == null) {
            // Manejar el caso en el que no se encontró el álbum
            JOptionPane.showMessageDialog(rootPane, "No se encontró el álbum seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar los campos de la canción
        if (txtNumero.getText().isBlank() || txtTitulo.getText().isBlank() || txtMinutos.getText().isBlank()
                || !txtMinutos.getText().matches("\\d+") || txtSegundos.getText().isBlank()
                || !txtSegundos.getText().matches("\\d+") || txtLetra.getText().isBlank()
                || txtGrabacion.getText().isBlank() || !txtGrabacion.getText().matches("\\d+")) {

            JOptionPane.showMessageDialog(rootPane, "Complete todos los campos para crear una Canción", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int numero = Integer.parseInt(txtNumero.getText());
            String titulo = txtTitulo.getText();
            int minutos = Integer.parseInt(txtMinutos.getText());
            int segundos = Integer.parseInt(txtSegundos.getText());
            String letra = txtLetra.getText();
            int anoGrabacion = Integer.parseInt(txtGrabacion.getText());

            // Verificar si la lista de canciones del álbum está inicializada
            if (albumSeleccionado.getCanciones() == null) {
                albumSeleccionado.setCanciones(new ArrayList<>());
            }

            // Crear una nueva canción
            Cancion nuevaCancion = new Cancion(numero, titulo, minutos, segundos, letra, anoGrabacion);

            // Asociar la canción al álbum seleccionado
            List<Cancion> cancionesAlbum = albumSeleccionado.getCanciones();
            cancionesAlbum.add(nuevaCancion);

            // Actualizar el modelo del JList con las canciones del álbum (si lo necesitas)
            DefaultListModel<String> modeloCancionesAlbum = (DefaultListModel<String>) lstCanciones.getModel();
            modeloCancionesAlbum.addElement(titulo);

            // Limpia los campos después de agregar la canción
            limpiarFormulario();

            JOptionPane.showMessageDialog(rootPane, "Datos de Canción Guardados", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Supongamos que tienes un método para cargar los álbumes en el JComboBox
    public void cargarAlbumesEnComboBox() {
        // Limpia el JComboBox
        cmbAlbumes.removeAllItems();

        // Itera sobre la lista de álbumes y agrega los nombres al JComboBox
        for (Album album : Utilitario.listaAlbum) {
            cmbAlbumes.addItem(album.getNombre());
        }
    }

    public void cargarListaCanciones() {

        // Limpiar el modelo antes de agregar elementos
        modelo.clear();

        // Iterar sobre la lista de artistas y agregar los nombres al modelo
        for (Cancion cancion : listaCanciones) {
            String titulo = cancion.getTitulo();
            modelo.addElement(titulo);
        }
    }

    public void eliminarCancionSeleccionada() {

        int indiceSeleccionado = lstCanciones.getSelectedIndex();

        if (indiceSeleccionado != -1) {
            Utilitario.eliminarCancion(listaCanciones, indiceSeleccionado);
        }
    }

    public void editarCancionSeleccionada() {
        int indiceSeleccionado = lstCanciones.getSelectedIndex();

        if (indiceSeleccionado != -1) {
            Utilitario.editarCancion(listaCanciones, indiceSeleccionado, txtNumero, txtTitulo, txtMinutos, txtSegundos, txtLetra, txtGrabacion);
        }
    }

    public void actualizarCancionSeleccionada() {
        int indiceSeleccionado = lstCanciones.getSelectedIndex();

        if (indiceSeleccionado != -1) {
            Utilitario.actualizarCancion(listaCanciones, indiceSeleccionado, txtNumero, txtTitulo, txtMinutos, txtSegundos, txtLetra, txtGrabacion);
        }
    }

    public void limpiarFormulario() {
        // Limpia los campos después de agregar el album
        txtNumero.setText("");
        txtTitulo.setText("");
        txtMinutos.setText("");
        txtSegundos.setText("");
        txtLetra.setText("");
        txtGrabacion.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCancion dialog = new frmCancion((frmPrincipal) new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditarArtista;
    private javax.swing.JButton btnEditarCancion;
    private javax.swing.JButton btnEliminarArtista;
    private javax.swing.JButton btnEliminarCancion;
    private javax.swing.JButton btnGuardarArtista;
    private javax.swing.JButton btnGuardarCancion;
    private javax.swing.JButton btnMostrarArtista;
    private javax.swing.JButton btnMostrarCancion;
    private javax.swing.JComboBox<String> cmbAlbumes;
    private javax.swing.JComboBox<String> cmbGeneros;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstArtistas;
    private javax.swing.JList<String> lstArtistas1;
    private javax.swing.JList<String> lstCanciones;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnBanda;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JRadioButton rbtnPausa;
    private javax.swing.JRadioButton rbtnSolista;
    private javax.swing.JTextField txtAnoInicial;
    private javax.swing.JTextField txtCantAlbumes;
    private javax.swing.JTextField txtCantCanciones;
    private javax.swing.JTextField txtGrabacion;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtNombreArtista;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtSegundos;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
