package Pantallas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author eefre
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {

        initComponents();

    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemCargarDatos = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        crudCancion = new javax.swing.JMenu();
        crudArtista = new javax.swing.JMenuItem();
        crudAlbum = new javax.swing.JMenuItem();
        itemCrudCancion = new javax.swing.JMenuItem();
        crudGenero = new javax.swing.JMenuItem();
        crudGeneroArtista = new javax.swing.JMenuItem();
        itemMostrar = new javax.swing.JMenu();
        itemInformacionGeneral = new javax.swing.JMenuItem();
        itemBusqueda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem13.setText("jMenuItem13");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" Sistema Gestor Musical Digital(SGMD) ");
        jLabel1.setMaximumSize(new java.awt.Dimension(206, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(206, 20));

        jLabel2.setText("Power By Evan & Mauricio, 2023");

        jMenu1.setText("Inicio");

        ItemCargarDatos.setText("Cargar Datos");
        ItemCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCargarDatosActionPerformed(evt);
            }
        });
        jMenu1.add(ItemCargarDatos);

        ItemSalir.setText("Salir");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(ItemSalir);

        jMenuBar1.add(jMenu1);

        crudCancion.setText("Mantenimiento");

        crudArtista.setText("Artista");
        crudArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudArtistaActionPerformed(evt);
            }
        });
        crudCancion.add(crudArtista);

        crudAlbum.setText("Álbum");
        crudAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudAlbumActionPerformed(evt);
            }
        });
        crudCancion.add(crudAlbum);

        itemCrudCancion.setText("Canción");
        itemCrudCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrudCancionActionPerformed(evt);
            }
        });
        crudCancion.add(itemCrudCancion);

        crudGenero.setText("Géneros");
        crudGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudGeneroActionPerformed(evt);
            }
        });
        crudCancion.add(crudGenero);

        crudGeneroArtista.setText("Géneros por artista");
        crudCancion.add(crudGeneroArtista);

        jMenuBar1.add(crudCancion);

        itemMostrar.setText("Consultas");

        itemInformacionGeneral.setText("Información general");
        itemInformacionGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionGeneralActionPerformed(evt);
            }
        });
        itemMostrar.add(itemInformacionGeneral);

        itemBusqueda.setText("Búsqueda");
        itemBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBusquedaActionPerformed(evt);
            }
        });
        itemMostrar.add(itemBusqueda);

        jMenuBar1.add(itemMostrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudArtistaActionPerformed
        frmArtista formArtistas = new frmArtista(this, true);

        formArtistas.setTitle("Artistas");
        formArtistas.setLocationRelativeTo(this);
        formArtistas.setResizable(false);
        formArtistas.setVisible(true);


    }//GEN-LAST:event_crudArtistaActionPerformed

    private void crudAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudAlbumActionPerformed
        frmAlbum formAlbum = new frmAlbum(this, true);

        formAlbum.setTitle("Albumes");
        formAlbum.setLocationRelativeTo(this);
        formAlbum.setResizable(false);
        formAlbum.setVisible(true);
    }//GEN-LAST:event_crudAlbumActionPerformed

    private void itemCrudCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrudCancionActionPerformed
        frmCancion formCancion = new frmCancion(this, true);

        formCancion.setTitle("Canciones");
        formCancion.setLocationRelativeTo(this);
        formCancion.setResizable(false);
        formCancion.setVisible(true);
    }//GEN-LAST:event_itemCrudCancionActionPerformed

    private void crudGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudGeneroActionPerformed
        frmGenero formGenero = new frmGenero(this, true);

        formGenero.setTitle("Genero");
        formGenero.setLocationRelativeTo(this);
        formGenero.setResizable(false);
        formGenero.setVisible(true);
    }//GEN-LAST:event_crudGeneroActionPerformed

    private void ItemCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCargarDatosActionPerformed
        Logica.Utilitario.inicializarDatosSistema();
        JOptionPane.showMessageDialog(null, "Datos Cargados con éxito");
    }//GEN-LAST:event_ItemCargarDatosActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        JOptionPane.showMessageDialog(null, "Saliendo del Sistema...");
        System.exit(0);
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void itemBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBusquedaActionPerformed
        frmFiltros formFiltros = new frmFiltros(this, true);

        formFiltros.setTitle("Artistas");
        formFiltros.setLocationRelativeTo(this);
        formFiltros.setResizable(false);
        formFiltros.setVisible(true);
    }//GEN-LAST:event_itemBusquedaActionPerformed

    private void itemInformacionGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionGeneralActionPerformed
        
         // Crear una instancia de frmInformacion
        frmInformacion forminfo = new frmInformacion();

        // Configurar la ventana
        forminfo.setTitle("Informacion General");
        forminfo.setLocationRelativeTo(this);
        forminfo.setResizable(false);

        // Hacer visible la ventana
        forminfo.setVisible(true);

      
    }//GEN-LAST:event_itemInformacionGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCargarDatos;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem crudAlbum;
    private javax.swing.JMenuItem crudArtista;
    private javax.swing.JMenu crudCancion;
    private javax.swing.JMenuItem crudGenero;
    private javax.swing.JMenuItem crudGeneroArtista;
    private javax.swing.JMenuItem itemBusqueda;
    private javax.swing.JMenuItem itemCrudCancion;
    private javax.swing.JMenuItem itemInformacionGeneral;
    private javax.swing.JMenu itemMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
